def get_district(city_name):
    city_to_district = {
        "colombo": "Colombo",
        "kesbewa": "Colombo",
        "moratuwa": "Colombo",
        "maharagama": "Colombo",
        "ratnapura": "Ratnapura",
        "kandy": "Kandy",
        "negombo": "Gampaha",
        "batticaloa": "Batticaloa",
        "mawanella": "Kegalle",
        "trincomalee": "Trincomalee",
        "kalmunai": "Ampara",
        "kotmale": "Nuwara Eliya",
        "kilinochchi": "Kilinochchi",
        "hikkaduwa": "Galle",
        "galle": "Galle",
        "jaffna": "Jaffna",
        "athurugiriya": "Colombo",
        "weligama": "Matara",
        "tangalla": "Hambantota",
        "kolonnawa": "Colombo",
        "matara": "Matara",
        "gampaha": "Gampaha",
        "akurana": "Kandy",
        "anuradhapura": "Anuradhapura",
        "puttalam": "Puttalam",
        "badulla": "Badulla",
        "matale": "Matale",
        "kalutara": "Kalutara",
        "bentota": "Galle",
        "mannar": "Mannar",
        "mabole": "Gampaha",
        "pothuhera": "Kegalle",
        "kurunegala": "Kurunegala",
        "hatton": "Nuwara Eliya",
        "galhinna": "Kegalle",
        "hambantota": "Hambantota",
        "abasingammedda": "Kandy",
        "kalpitiya": "Puttalam",
        "tissamaharama": "Hambantota",
        "dambulla": "Matale",
        "galgamuwa": "Kurunegala",
        "dikwella": "Matara",
        "kalawana": "Ratnapura",
        "nikaweratiya": "Kurunegala",
        "bakamune": "Kegalle",
        "sevanagala": "Ratnapura",
        "vavuniya": "Vavuniya",
        "gampola": "Kandy",
        "mullaittivu": "Mullaitivu",
        "hakmana": "Matara",
        "kegalle": "Kegalle",
        "gandara": "Matara",
        "monaragala": "Monaragala",
        "panadura": "Kalutara",
        "rajagiriya": "Colombo",
        "kosgama": "Colombo",
        "keselwatta": "Colombo",
        "galkissa": "Colombo",
        "dehiwala": "Colombo",
        "sri jayawardenepura kotte": "Colombo",
        "mount lavinia": "Colombo",
        "nuwara eliya": "NuwaraEliya",
        "point pedro": "Jaffna",
        "polonnaruwa": "Polonnaruwa",
        "medirigiriya": "Polonnaruwa",
        "mannar": "Mannar",
        "kilinochchi": "Kilinochchi"
    }
    city_name = city_name.strip().lower()

    if city_name in city_to_district:
        return city_to_district[city_name]
    else:
        return None